.TH "src Directory Reference" 3 "Sun Mar 12 2017" "REDES2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src Directory Reference \- 
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBG-2301-05-P1-client\&.c\fP"
.br
.ti -1c
.RI "file \fBG-2301-05-P1-commands\&.c\fP"
.br
.ti -1c
.RI "file \fBG-2301-05-P1-getCommandList\&.c\fP"
.br
.ti -1c
.RI "file \fBG-2301-05-P1-server\&.c\fP"
.br
.ti -1c
.RI "file \fBG-2301-05-P1-socket\&.c\fP"
.br
.ti -1c
.RI "file \fBG-2301-05-P1-tools\&.c\fP"
.br
.ti -1c
.RI "file \fBG-2301-05-P1-xchat2\&.c\fP"
.br
.in -1c
