.TH "src/G-2301-05-P1-socket.c" 3 "Sun Mar 12 2017" "REDES2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/G-2301-05-P1-socket.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include '\&.\&./includes/G-2301-05-P1-socket\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBopenSocket_TCP\fP ()"
.br
.RI "\fIabre un socket \fP"
.ti -1c
.RI "int \fBbindSocket_TCP\fP (int sockfd, int portno, struct sockaddr_in *serv_addr)"
.br
.RI "\fIenlaza un socket con un puerto a la vez que rellena los campos de la estructura sockaddr_in de serv_addr \fP"
.ti -1c
.RI "int \fBacceptConnection\fP (int sockfd, struct sockaddr_in *cli_addr)"
.br
.RI "\fIprepara un socket para aceptar una conexión entrante \fP"
.ti -1c
.RI "int \fBconnectTo\fP (int sockfd, char *\fBhostname\fP, int portno)"
.br
.RI "\fItrata de conectarse a un puerto de un host \fP"
.in -1c
.SH "Function Documentation"
.PP 
.SS "int acceptConnection (intsockfd, struct sockaddr_in *cli_addr)"

.PP
prepara un socket para aceptar una conexión entrante 
.PP
\fBParameters:\fP
.RS 4
\fIsockfd\fP el socket que está escuchando conexiones entrantes 
.br
\fIcli_addr\fP la dirección de una estructura sockaddr_in donde se rellenaran los valores relativos al otro extremo de la conexión
.RE
.PP
\fBReturns:\fP
.RS 4
-1 en caso de error y un nuevo socket (valor mayor que 0) en el que se mantendrá la comunicación con el otro extremo 
.RE
.PP

.SS "int bindSocket_TCP (intsockfd, intportno, struct sockaddr_in *serv_addr)"

.PP
enlaza un socket con un puerto a la vez que rellena los campos de la estructura sockaddr_in de serv_addr 
.PP
\fBParameters:\fP
.RS 4
\fIsockfd\fP el socket a enlazar 
.br
\fIportno\fP el puerto al que enlazar el socket 
.br
\fIserv_addr\fP la dirección de una estructura sockaddr_in en donde se guardarán los valores relativos a esta conexión
.RE
.PP
\fBReturns:\fP
.RS 4
-1 en caso de error, un numero positivo en otro caso 
.RE
.PP

.SS "int connectTo (intsockfd, char *hostname, intportno)"

.PP
trata de conectarse a un puerto de un host 
.PP
\fBParameters:\fP
.RS 4
\fIsockfd\fP el socket que intentará realizar la conexión 
.br
\fIhostname\fP el nombre de la maquina a la que se desea conectarse 
.br
\fIportno\fP el puerto al que se desea conectar
.RE
.PP
\fBReturns:\fP
.RS 4
en caso de error, un valor negativo\&. De lo contrario, un nuevo socket en el que se mantendrá la comunicación con el otro extremo 
.RE
.PP

.SS "int openSocket_TCP ()"

.PP
abre un socket 
.PP
\fBReturns:\fP
.RS 4
el socket o -1 en caso de que hubiera un fallo 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for REDES2 from the source code\&.
