.TH "threadArgs" 3 "Sun Mar 12 2017" "REDES2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
threadArgs \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "int \fBsocket\fP"
.br
.ti -1c
.RI "struct sockaddr_in * \fBclient\fP"
.br
.ti -1c
.RI "struct sockaddr_in * \fBserver\fP"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "struct sockaddr_in* threadArgs::client"

.SS "struct sockaddr_in* threadArgs::server"

.SS "int threadArgs::socket"


.SH "Author"
.PP 
Generated automatically by Doxygen for REDES2 from the source code\&.
