.TH "/home/javier/Escritorio/Redes/G-2301-05-P3/src Directory Reference" 3 "Sun May 7 2017" "Redes2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/javier/Escritorio/Redes/G-2301-05-P3/src Directory Reference \- 
.SH SYNOPSIS
.br
.PP
.SS "Directories"

.in +1c
.ti -1c
.RI "directory \fBdaemonizar\fP"
.br
.in -1c
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBcliente_echo\&.c\fP"
.br
.ti -1c
.RI "file \fBcliente_IRC\&.c\fP"
.br
.ti -1c
.RI "file \fBG-2301-05-P1-client\&.c\fP"
.br
.ti -1c
.RI "file \fBG-2301-05-P1-commands\&.c\fP"
.br
.ti -1c
.RI "file \fBG-2301-05-P1-server\&.c\fP"
.br
.ti -1c
.RI "file \fBG-2301-05-P2-audio\&.c\fP"
.br
.ti -1c
.RI "file \fBG-2301-05-P2-basicCommandsFromServer\&.c\fP"
.br
.ti -1c
.RI "file \fBG-2301-05-P2-repliesFromServer\&.c\fP"
.br
.ti -1c
.RI "file \fBG-2301-05-P2-userCommands\&.c\fP"
.br
.ti -1c
.RI "file \fBG-2301-05-P2-userTools\&.c\fP"
.br
.ti -1c
.RI "file \fBG-2301-05-P2-xchat2\&.c\fP"
.br
.ti -1c
.RI "file \fBservidor_echo\&.c\fP"
.br
.ti -1c
.RI "file \fBservidor_IRC\&.c\fP"
.br
.in -1c
