.TH "/home/javier/Escritorio/Redes/G-2301-05-P3/src/cliente_echo.c" 3 "Sun May 7 2017" "Redes2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/javier/Escritorio/Redes/G-2301-05-P3/src/cliente_echo.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include '\&.\&./includes/G-2301-05-P3-ssl\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBmain\fP (int argc, char *argv[])"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "int main (intargc, char *argv[])"
Cliente Echo Se encarga de crear una conexión segura donde se manda al servidor lo escrito por terminal y se dedica a imprimir lo que recibe Si escribes exit acaba su ejecución 
.PP
\fBReturns:\fP
.RS 4
0 si es correcto, -1 si no 
.RE
.PP

.PP
Definition at line 8 of file cliente_echo\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Redes2 from the source code\&.
