.TH "/home/javier/Escritorio/Redes/G-2301-05-P3/src/daemonizar/daemonizar.h" 3 "Sun May 7 2017" "Redes2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/javier/Escritorio/Redes/G-2301-05-P3/src/daemonizar/daemonizar.h \- 
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBdaemonizar\fP ()"
.br
.RI "\fIdaemoniza el proceso el proceso queda en segundo plano como proceso de init \fP"
.in -1c
.SH "Function Documentation"
.PP 
.SS "void daemonizar ()"

.PP
daemoniza el proceso el proceso queda en segundo plano como proceso de init 
.PP
Definition at line 9 of file G-2301-05-P1-tools\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Redes2 from the source code\&.
