.TH "G-2301-05-P1-socket.h" 3 "Sun May 7 2017" "Redes2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
G-2301-05-P1-socket.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'G-2301-05-P1-tools\&.h'\fP
.br
\fC#include <sys/socket\&.h>\fP
.br
\fC#include <netinet/in\&.h>\fP
.br
\fC#include <arpa/inet\&.h>\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBSERVERINFO\fP   'servidor de Mambru, DoReMi DoReFa'"
.br
.ti -1c
.RI "#define \fBSERVERNAME\fP   'Mambru@war'"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBopenSocket_TCP\fP ()"
.br
.RI "\fIabre un socket TCP \fP"
.ti -1c
.RI "int \fBbindSocket_TCP\fP (int \fBsockfd\fP, int portno, struct sockaddr_in *serv_addr)"
.br
.RI "\fIenlaza un socket TCP con un puerto a la vez que rellena los campos de la estructura sockaddr_in de serv_addr \fP"
.ti -1c
.RI "int \fBacceptConnection\fP (int \fBsockfd\fP, struct sockaddr_in *client_addr)"
.br
.RI "\fIprepara un socket para aceptar una conexión entrante \fP"
.ti -1c
.RI "int \fBconnectTo\fP (int \fBsockfd\fP, char *\fBhostname\fP, int portno)"
.br
.RI "\fItrata de conectarse a un puerto de un host \fP"
.ti -1c
.RI "int \fBconnectToIP\fP (int \fBsockfd\fP, char *IP, int portno)"
.br
.RI "\fItrata de conectarse a un puerto de una IP \fP"
.ti -1c
.RI "int \fBopenSocket_UDP\fP ()"
.br
.RI "\fIabre un socket UDP \fP"
.ti -1c
.RI "int \fBbindSocket_UDP\fP (int \fBsockfd\fP, int portno, struct sockaddr_in *serv_addr)"
.br
.RI "\fIenlaza un socket UDP con un puerto a la vez que rellena los campos de la estructura sockaddr_in de serv_addr \fP"
.ti -1c
.RI "int \fBgetSocketPort\fP (int \fBsockfd\fP, struct sockaddr_in *serv_addr)"
.br
.RI "\fIobtiene el puerto al que ha sido enlazado el socket sockfd y tambien rellena los campos de serv \fP"
.ti -1c
.RI "int \fBiniAddrUDP\fP (struct sockaddr_in *si_other, int port, char *\fBhostname\fP)"
.br
.RI "\fIinicializa correctamente la estructura con datos para una conexion UDP \fP"
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define SERVERINFO   'servidor de Mambru, DoReMi DoReFa'"

.PP
Definition at line 10 of file G-2301-05-P1-socket\&.h\&.
.SS "#define SERVERNAME   'Mambru@war'"

.PP
Definition at line 11 of file G-2301-05-P1-socket\&.h\&.
.SH "Function Documentation"
.PP 
.SS "int acceptConnection (intsockfd, struct sockaddr_in *cli_addr)"

.PP
prepara un socket para aceptar una conexión entrante 
.PP
\fBParameters:\fP
.RS 4
\fIsockfd\fP el socket que está escuchando conexiones entrantes 
.br
\fIcli_addr\fP la dirección de una estructura sockaddr_in donde se rellenaran los valores relativos al otro extremo de la conexión
.RE
.PP
\fBReturns:\fP
.RS 4
-1 en caso de error y un nuevo socket (valor mayor que 0) en el que se mantendrá la comunicación con el otro extremo 
.RE
.PP

.PP
Definition at line 82 of file G-2301-05-P1-socket\&.c\&.
.SS "int bindSocket_TCP (intsockfd, intportno, struct sockaddr_in *serv_addr)"

.PP
enlaza un socket TCP con un puerto a la vez que rellena los campos de la estructura sockaddr_in de serv_addr 
.PP
\fBParameters:\fP
.RS 4
\fIsockfd\fP el socket a enlazar 
.br
\fIportno\fP el puerto al que enlazar el socket 
.br
\fIserv_addr\fP la dirección de una estructura sockaddr_in en donde se guardarán los valores relativos a esta conexión
.RE
.PP
\fBReturns:\fP
.RS 4
-1 en caso de error, un numero positivo en otro caso 
.RE
.PP

.PP
Definition at line 59 of file G-2301-05-P1-socket\&.c\&.
.SS "int bindSocket_UDP (intsockfd, intportno, struct sockaddr_in *serv_addr)"

.PP
enlaza un socket UDP con un puerto a la vez que rellena los campos de la estructura sockaddr_in de serv_addr 
.PP
\fBParameters:\fP
.RS 4
\fIsockfd\fP el socket a enlazar 
.br
\fIportno\fP el puerto al que enlazar el socket 
.br
\fIserv_addr\fP la dirección de una estructura sockaddr_in en donde se guardarán los valores relativos a esta conexión
.RE
.PP
\fBReturns:\fP
.RS 4
-1 en caso de error, un numero positivo en otro caso 
.RE
.PP

.PP
Definition at line 165 of file G-2301-05-P1-socket\&.c\&.
.SS "int connectTo (intsockfd, char *hostname, intportno)"

.PP
trata de conectarse a un puerto de un host 
.PP
\fBParameters:\fP
.RS 4
\fIsockfd\fP el socket que intentará realizar la conexión 
.br
\fIhostname\fP el nombre de la maquina a la que se desea conectarse 
.br
\fIportno\fP el puerto al que se desea conectar
.RE
.PP
\fBReturns:\fP
.RS 4
en caso de error, un valor negativo\&. De lo contrario, un nuevo socket en el que se mantendrá la comunicación con el otro extremo 
.RE
.PP

.PP
Definition at line 103 of file G-2301-05-P1-socket\&.c\&.
.SS "int connectToIP (intsockfd, char *IP, intportno)"

.PP
trata de conectarse a un puerto de una IP 
.PP
\fBParameters:\fP
.RS 4
\fIsockfd\fP el socket que intentará realizar la conexión 
.br
\fIIP\fP la dirección IP en notación estándar a la que conectarse 
.br
\fIportno\fP el puerto al que se desea conectar
.RE
.PP
\fBReturns:\fP
.RS 4
en caso de error, un valor negativo\&. De lo contrario, un nuevo socket en el que se mantendrá la comunicación con el otro extremo 
.RE
.PP

.PP
Definition at line 131 of file G-2301-05-P1-socket\&.c\&.
.SS "int getSocketPort (intsockfd, struct sockaddr_in *serv)"

.PP
obtiene el puerto al que ha sido enlazado el socket sockfd y tambien rellena los campos de serv 
.PP
\fBParameters:\fP
.RS 4
\fIsockfd\fP el socket (enlazado) del que queremos sacar su puerto 
.br
\fIserv\fP la estructura sockaddr_in en la que se guardan los datos referentes a nuestro extremo de la conexion
.RE
.PP
\fBReturns:\fP
.RS 4
el puerto del socket\&. Si hubo un error, -1 
.RE
.PP

.PP
Definition at line 188 of file G-2301-05-P1-socket\&.c\&.
.SS "int iniAddrUDP (struct sockaddr_in *si_other, intport, char *hostname)"

.PP
inicializa correctamente la estructura con datos para una conexion UDP 
.PP
\fBParameters:\fP
.RS 4
\fIsi_other\fP la estructura que se inicializara 
.br
\fIport\fP el puerto del otro sistema con el que se desea comunicar 
.br
\fIhostname\fP el hostname del otro sistema con el que se desea comunicar
.RE
.PP
\fBReturns:\fP
.RS 4
-1 si hubo un error, IRC_OK si todo fue bien 
.RE
.PP

.PP
Definition at line 24 of file G-2301-05-P1-socket\&.c\&.
.SS "int openSocket_TCP ()"

.PP
abre un socket TCP 
.PP
\fBReturns:\fP
.RS 4
el socket o -1 en caso de que hubiera un fallo 
.RE
.PP

.PP
Definition at line 8 of file G-2301-05-P1-socket\&.c\&.
.SS "int openSocket_UDP ()"

.PP
abre un socket UDP 
.PP
\fBReturns:\fP
.RS 4
el socket o -1 en caso de que hubiera un fallo 
.RE
.PP

.PP
Definition at line 149 of file G-2301-05-P1-socket\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Redes2 from the source code\&.
