.TH "G-2301-05-P1-types.h" 3 "Sun May 7 2017" "Redes2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
G-2301-05-P1-types.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <stdlib\&.h>\fP
.br
\fC#include <stdio\&.h>\fP
.br
\fC#include <string\&.h>\fP
.br
\fC#include <unistd\&.h>\fP
.br
\fC#include <netdb\&.h>\fP
.br
\fC#include <stdint\&.h>\fP
.br
\fC#include <syslog\&.h>\fP
.br
\fC#include <errno\&.h>\fP
.br
\fC#include <pthread\&.h>\fP
.br
\fC#include <sys/types\&.h>\fP
.br
\fC#include <sys/socket\&.h>\fP
.br
\fC#include <sys/stat\&.h>\fP
.br
\fC#include <sys/time\&.h>\fP
.br
\fC#include <netinet/in\&.h>\fP
.br
\fC#include <redes2/irc\&.h>\fP
.br
\fC#include <redes2/irctad\&.h>\fP
.br
\fC#include <redes2/ircxchat\&.h>\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBCLIENTNAME\fP   'JohnTitor'"
.br
.ti -1c
.RI "#define \fBERROR\fP   -1"
.br
.ti -1c
.RI "#define \fBERROR_SEND\fP   -2"
.br
.ti -1c
.RI "#define \fBERROR_RECV\fP   -3"
.br
.ti -1c
.RI "#define \fBERROR_MALLOC\fP   -4"
.br
.ti -1c
.RI "#define \fBERROR_CONTINUE\fP   -5"
.br
.ti -1c
.RI "#define \fBMACRO_QUIT\fP   -6"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define CLIENTNAME   'JohnTitor'"

.PP
Definition at line 24 of file G-2301-05-P1-types\&.h\&.
.SS "#define ERROR   -1"

.PP
Definition at line 25 of file G-2301-05-P1-types\&.h\&.
.SS "#define ERROR_CONTINUE   -5"

.PP
Definition at line 29 of file G-2301-05-P1-types\&.h\&.
.SS "#define ERROR_MALLOC   -4"

.PP
Definition at line 28 of file G-2301-05-P1-types\&.h\&.
.SS "#define ERROR_RECV   -3"

.PP
Definition at line 27 of file G-2301-05-P1-types\&.h\&.
.SS "#define ERROR_SEND   -2"

.PP
Definition at line 26 of file G-2301-05-P1-types\&.h\&.
.SS "#define MACRO_QUIT   -6"

.PP
Definition at line 30 of file G-2301-05-P1-types\&.h\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Redes2 from the source code\&.
