.TH "/home/javier/Escritorio/Redes/G-2301-05-P3/srclib/G-2301-05-P3-ssl.c" 3 "Sun May 7 2017" "Redes2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/javier/Escritorio/Redes/G-2301-05-P3/srclib/G-2301-05-P3-ssl.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include '\&.\&./includes/G-2301-05-P3-ssl\&.h'\fP
.br
\fC#include <err\&.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBinicializar_nivel_SSL\fP ()"
.br
.ti -1c
.RI "SSL_CTX * \fBfijar_contexto_SSL\fP (char *CAfile, char *SCfile, char *Pfile, char *CApath)"
.br
.ti -1c
.RI "SSL * \fBconectar_canal_seguro_SSL\fP (SSL_CTX *ctx, int \fBsockfd\fP)"
.br
.ti -1c
.RI "SSL * \fBaceptar_canal_seguro_SSL\fP (SSL_CTX *ctx, int \fBsockfd\fP)"
.br
.ti -1c
.RI "boolean \fBevaluar_post_connectar_SSL\fP (SSL *ssl)"
.br
.ti -1c
.RI "int \fBenviar_datos_SSL\fP (SSL *ssl, void *buf, int num)"
.br
.ti -1c
.RI "int \fBrecibir_datos_SSL\fP (SSL *ssl, void *buf, int num)"
.br
.ti -1c
.RI "int \fBcerrar_canal_SSL\fP (SSL *ssl, SSL_CTX *ctx, int \fBsockfd\fP)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "SSL* aceptar_canal_seguro_SSL (SSL_CTX *ctx, intsockfd)"
Dado un contexto SSL y un descriptor de socket esta función se encargará de bloquear la aplicación, que se quedará esperando hasta recibir un handshake por parte del cliente\&. 
.PP
\fBParameters:\fP
.RS 4
\fIctx\fP contexto de la conexión segura 
.br
\fIsockfd\fP socket de la conexión segura 
.RE
.PP
\fBReturns:\fP
.RS 4
estructura SSL de la conexión segura 
.RE
.PP

.PP
Definition at line 82 of file G-2301-05-P3-ssl\&.c\&.
.SS "int cerrar_canal_SSL (SSL *ssl, SSL_CTX *ctx, intsockfd)"
Esta función liberará todos los recursos y cerrará el canal de comunicación seguro creado previamente\&. 
.PP
\fBParameters:\fP
.RS 4
\fIssl\fP estructura SSL de la conexión segura 
.br
\fIctx\fP contexto de la conexión segura 
.br
\fIsockfd\fP socket de la conexión segura 
.RE
.PP
\fBReturns:\fP
.RS 4
1 si ha ido bien, -1 si ha habido un fallo 
.RE
.PP

.PP
Definition at line 155 of file G-2301-05-P3-ssl\&.c\&.
.SS "SSL* conectar_canal_seguro_SSL (SSL_CTX *ctx, intsockfd)"
Dado un contexto SSL y un descriptor de socket esta función se encargará de obtener un canal seguro SSL iniciando el proceso de handshake con el otro extremo\&. 
.PP
\fBParameters:\fP
.RS 4
\fIctx\fP contexto de la conexión segura 
.br
\fIsockfd\fP socket de la conexión segura 
.RE
.PP
\fBReturns:\fP
.RS 4
estructura SSL de la conexión segura 
.RE
.PP

.PP
Definition at line 57 of file G-2301-05-P3-ssl\&.c\&.
.SS "int enviar_datos_SSL (SSL *ssl, void *buf, intnum)"
Esta función será el equivalente a la función de envío de mensajes que se realizó en la práctica 1, pero será utilizada para enviar datos a través del canal seguro\&. Es importante que sea genérica y pueda ser utilizada independientemente de los datos que se vayan a enviar\&. 
.PP
\fBParameters:\fP
.RS 4
\fIssl\fP estructura SSL de la conexión segura 
.br
\fIbuf\fP datos a enviar 
.br
\fInum\fP tamaño de los datos 
.RE
.PP
\fBReturns:\fP
.RS 4
numero >0 si ha ido bien <=0 si no 
.RE
.PP

.PP
Definition at line 129 of file G-2301-05-P3-ssl\&.c\&.
.SS "boolean evaluar_post_connectar_SSL (SSL *ssl)"
Esta función comprobará una vez realizado el handshake que el canal de co- municación se puede considerar seguro\&. 
.PP
\fBParameters:\fP
.RS 4
\fIssl\fP estructura SSL de la conexión segura 
.RE
.PP
\fBReturns:\fP
.RS 4
true si es seguro, false si no 
.RE
.PP

.PP
Definition at line 106 of file G-2301-05-P3-ssl\&.c\&.
.SS "SSL_CTX* fijar_contexto_SSL (char *CAfile, char *SCfile, char *Pfile, char *CApath)"
Esta función se encargará de inicializar correctamente el contexto que será utilizado para la creación de canales seguros mediante SSL\&. Deberá recibir información sobre las rutas a los certificados y claves con los que vaya a trabajar la aplicación\&. 
.PP
\fBParameters:\fP
.RS 4
\fICAfile\fP certificado de la CA 
.br
\fISCfile\fP certificado del servidor/cliente 
.br
\fIPfile\fP clave privada del servidor/cliente 
.br
\fICApath\fP ruta del certificado de la CA 
.RE
.PP
\fBReturns:\fP
.RS 4
contexto de la conexión segura 
.RE
.PP

.PP
Definition at line 23 of file G-2301-05-P3-ssl\&.c\&.
.SS "void inicializar_nivel_SSL ()"
Esta función se encargará de realizar todas las llamadas necesarias para que la apli- cación pueda usar la capa segura SSL\&. 
.PP
Definition at line 8 of file G-2301-05-P3-ssl\&.c\&.
.SS "int recibir_datos_SSL (SSL *ssl, void *buf, intnum)"
Esta función será el equivalente a la función de lectura de mensajes que se realizó en la práctica 1, pero será utilizada para enviar datos a través del canal seguro\&. Es importante que sea genérica y pueda ser utilizada independientemente de los datos que se vayan a recibir\&. 
.PP
\fBParameters:\fP
.RS 4
\fIssl\fP estructura SSL de la conexión segura 
.br
\fIbuf\fP datos a recibir 
.br
\fInum\fP tamaño de los datos 
.RE
.PP
\fBReturns:\fP
.RS 4
numero >0 si ha ido bien <=0 si no 
.RE
.PP

.PP
Definition at line 142 of file G-2301-05-P3-ssl\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Redes2 from the source code\&.
