.TH "/home/javier/Escritorio/Redes/G-2301-05-P3/src/servidor_echo.c" 3 "Sun May 7 2017" "Redes2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/javier/Escritorio/Redes/G-2301-05-P3/src/servidor_echo.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include '\&.\&./includes/G-2301-05-P3-ssl\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBmain\fP (int argc, char *argv[])"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "int main (intargc, char *argv[])"
Servidor Echo Este servidor se encarga de crear una conexión segura donde se limita a recibir datos de un cliente y devolvérselos inmediatamente Si recibe un exit finaliza 
.PP
\fBReturns:\fP
.RS 4
0 si todo fue bien, -1 si hubo algún error 
.RE
.PP

.PP
Definition at line 8 of file servidor_echo\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Redes2 from the source code\&.
