.TH "threadArgs" 3 "Sun May 7 2017" "Redes2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
threadArgs \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "int \fBsocket\fP"
.br
.ti -1c
.RI "struct sockaddr_in * \fBclient\fP"
.br
.ti -1c
.RI "struct sockaddr_in * \fBserver\fP"
.br
.ti -1c
.RI "SSL * \fBssl\fP"
.br
.ti -1c
.RI "SSL_CTX * \fBctx\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 11 of file G-2301-05-P1-server\&.c\&.
.SH "Field Documentation"
.PP 
.SS "struct sockaddr_in * client"

.PP
Definition at line 13 of file G-2301-05-P1-server\&.c\&.
.SS "SSL_CTX* ctx"

.PP
Definition at line 18 of file servidor_IRC\&.c\&.
.SS "struct sockaddr_in * server"

.PP
Definition at line 14 of file G-2301-05-P1-server\&.c\&.
.SS "int socket"

.PP
Definition at line 12 of file G-2301-05-P1-server\&.c\&.
.SS "SSL* ssl"

.PP
Definition at line 17 of file servidor_IRC\&.c\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Redes2 from the source code\&.
