.TH "userTools" 3 "Sun May 7 2017" "Redes2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
userTools \- 
Funciones auxiliares para el cliente
.PP
.PP
 printXchat
imprime el mensaje del final del reply por la interfaz
.PP
\fBParameters:\fP
.RS 4
\fIchannel\fP canal donde se escribe, o null si es en system 
.br
\fInick\fP nick del usuario que lo manda 
.br
\fImsg\fP reply de la cual imprimimos el ultimo campo 
.br
\fIthread\fP T si es la version con threads, false, si no
.RE
.PP
.PP
 
.SS "getMyNick"
funcion que devuelve el nick asociado a este cliente\&. version para ser llamada en algun callback de la interfaz
.PP
\fBReturns:\fP
.RS 4
el nick asociado a este cliente
.RE
.PP
.PP
 
.SS "getMyNickThread"
funcion que devuelve el nick asociado a este cliente\&. version para ser llamada por los hilos del cliente
.PP
\fBReturns:\fP
.RS 4
el nick asociado a este cliente
.RE
.PP
.PP
 
.SH "Author"
.PP 
Generated automatically by Doxygen for Redes2 from the source code\&.
