.TH "/home/javier/Escritorio/Redes/G-2301-05-P3/src/daemonizar/daemonizar.c" 3 "Sun May 7 2017" "Redes2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/javier/Escritorio/Redes/G-2301-05-P3/src/daemonizar/daemonizar.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include <stdint\&.h>\fP
.br
\fC#include <stdlib\&.h>\fP
.br
\fC#include <unistd\&.h>\fP
.br
\fC#include <syslog\&.h>\fP
.br
\fC#include <stdio\&.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBdaemonizar\fP ()"
.br
.RI "\fIdaemoniza el proceso el proceso queda en segundo plano como proceso de init \fP"
.in -1c
.SH "Function Documentation"
.PP 
.SS "void daemonizar ()"

.PP
daemoniza el proceso el proceso queda en segundo plano como proceso de init 
.PP
Definition at line 7 of file daemonizar\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Redes2 from the source code\&.
