.TH "serverCommands" 3 "Sun May 7 2017" "Redes2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
serverCommands \- 
Funciones que se encargan del procesado de los comandos que llegan desde el cliente
.PP
.PP
 commandDefault
commando por defecto envía un mensaje de error al cliente, indicando que el comando introducido es invalido
.PP
\fBParameters:\fP
.RS 4
\fIsocket\fP el socket del usuario a ver 
.br
\fIclient\fP los datos del dispositivo cliente 
.br
\fIserver\fP los datos del dispositivo servidor 
.br
\fIstrin\fP el commando recibido
.RE
.PP
\fBReturns:\fP
.RS 4
IRC_OK si fue bien, otra cosa si no
.RE
.PP
.PP
 
.SS "commandNick"
commando nick permite al usuario cambiar de nickname
.PP
\fBParameters:\fP
.RS 4
\fIsocket\fP el socket del usuario a ver 
.br
\fIclient\fP los datos del dispositivo cliente 
.br
\fIserver\fP los datos del dispositivo servidor 
.br
\fIstrin\fP el commando recibido
.RE
.PP
\fBReturns:\fP
.RS 4
IRC_OK si fue bien, otra cosa si no
.RE
.PP
.PP
 
.SS "commandMode"
commando mode permite al usuario cambiar el modo un canal especificado
.PP
\fBParameters:\fP
.RS 4
\fIsocket\fP el socket del usuario a ver 
.br
\fIclient\fP los datos del dispositivo cliente 
.br
\fIserver\fP los datos del dispositivo servidor 
.br
\fIstrin\fP el commando recibido
.RE
.PP
\fBReturns:\fP
.RS 4
IRC_OK si fue bien, otra cosa si no
.RE
.PP
.PP
 
.SS "commandQuit"
commando quit permite al usuario abandonar el servidor
.PP
\fBParameters:\fP
.RS 4
\fIsocket\fP el socket del usuario a ver 
.br
\fIclient\fP los datos del dispositivo cliente 
.br
\fIserver\fP los datos del dispositivo servidor 
.br
\fIstrin\fP el commando recibido
.RE
.PP
\fBReturns:\fP
.RS 4
IRC_OK si fue bien, otra cosa si no
.RE
.PP
.PP
 
.SS "commandJoin"
commando join permite al usuario unirse a un canal\&. En caso de que se requiera una password para unirse, el usuario debería incluirla en el comando tal y como se indica en el RFC\&. Tratar de unirse a un canal inexistente, creará dicho canal
.PP
\fBParameters:\fP
.RS 4
\fIsocket\fP el socket del usuario a ver 
.br
\fIclient\fP los datos del dispositivo cliente 
.br
\fIserver\fP los datos del dispositivo servidor 
.br
\fIstrin\fP el commando recibido
.RE
.PP
\fBReturns:\fP
.RS 4
IRC_OK si fue bien, otra cosa si no
.RE
.PP
.PP
 
.SS "commandPart"
commando part permite al usuario abandonar el canal indicado\&. Si se trata de abandonar un canal invalido se le enviará un mensaje de notificación al cliente
.PP
\fBParameters:\fP
.RS 4
\fIsocket\fP el socket del usuario a ver 
.br
\fIclient\fP los datos del dispositivo cliente 
.br
\fIserver\fP los datos del dispositivo servidor 
.br
\fIstrin\fP el commando recibido
.RE
.PP
\fBReturns:\fP
.RS 4
IRC_OK si fue bien, otra cosa si no
.RE
.PP
.PP
 
.SS "commandTopic"
commando topic permite al usuario consultar el topic de un canal especificado o bien cambiar el mismo
.PP
\fBParameters:\fP
.RS 4
\fIsocket\fP el socket del usuario a ver 
.br
\fIclient\fP los datos del dispositivo cliente 
.br
\fIserver\fP los datos del dispositivo servidor 
.br
\fIstrin\fP el commando recibido
.RE
.PP
\fBReturns:\fP
.RS 4
IRC_OK si fue bien, otra cosa si no
.RE
.PP
.PP
 
.SS "commandNames"
commando mode permite al usuario obtener la lista de nicknames de usuarios que pertenezcan a un canal
.PP
\fBParameters:\fP
.RS 4
\fIsocket\fP el socket del usuario a ver 
.br
\fIclient\fP los datos del dispositivo cliente 
.br
\fIserver\fP los datos del dispositivo servidor 
.br
\fIstrin\fP el commando recibido
.RE
.PP
\fBReturns:\fP
.RS 4
IRC_OK si fue bien, otra cosa si no
.RE
.PP
.PP
 
.SS "commandList"
commando list permite al usuario obtener la lista de canales del servidor o bien información sobre un canal en partiular
.PP
\fBParameters:\fP
.RS 4
\fIsocket\fP el socket del usuario a ver 
.br
\fIclient\fP los datos del dispositivo cliente 
.br
\fIserver\fP los datos del dispositivo servidor 
.br
\fIstrin\fP el commando recibido
.RE
.PP
\fBReturns:\fP
.RS 4
IRC_OK si fue bien, otra cosa si no
.RE
.PP
.PP
 
.SS "commandKick"
commando kick permite al usuario expulsar a un usuario de un canal (siempre y cuando se sea operador del canal)
.PP
\fBParameters:\fP
.RS 4
\fIsocket\fP el socket del usuario a ver 
.br
\fIclient\fP los datos del dispositivo cliente 
.br
\fIserver\fP los datos del dispositivo servidor 
.br
\fIstrin\fP el commando recibido
.RE
.PP
\fBReturns:\fP
.RS 4
IRC_OK si fue bien, otra cosa si no
.RE
.PP
.PP
 
.SS "commandPrivmsg"
commando Privmsg permite al usuario enviar mensajes tanto a un usuario en concreto como a todos los usuarios de un canal
.PP
\fBParameters:\fP
.RS 4
\fIsocket\fP el socket del usuario a ver 
.br
\fIclient\fP los datos del dispositivo cliente 
.br
\fIserver\fP los datos del dispositivo servidor 
.br
\fIstrin\fP el commando recibido
.RE
.PP
\fBReturns:\fP
.RS 4
IRC_OK si fue bien, otra cosa si no
.RE
.PP
.PP
 
.SS "commandMotd"
commando Message of the Day permite al usuario consultar el mensaje del día
.PP
\fBParameters:\fP
.RS 4
\fIsocket\fP el socket del usuario a ver 
.br
\fIclient\fP los datos del dispositivo cliente 
.br
\fIserver\fP los datos del dispositivo servidor 
.br
\fIstrin\fP el commando recibido
.RE
.PP
\fBReturns:\fP
.RS 4
IRC_OK si fue bien, otra cosa si no
.RE
.PP
.PP
 
.SS "commandWhois"
commando Whois permite al usuario obtener información de cierto usuario en el servidor
.PP
\fBParameters:\fP
.RS 4
\fIsocket\fP el socket del usuario a ver 
.br
\fIclient\fP los datos del dispositivo cliente 
.br
\fIserver\fP los datos del dispositivo servidor 
.br
\fIstrin\fP el commando recibido
.RE
.PP
\fBReturns:\fP
.RS 4
IRC_OK si fue bien, otra cosa si no
.RE
.PP
.PP
 
.SS "commandPing"
commando Ping permite al usuario comprobar que la conexion con el servidor sigue estando activa
.PP
\fBParameters:\fP
.RS 4
\fIsocket\fP el socket del usuario a ver 
.br
\fIclient\fP los datos del dispositivo cliente 
.br
\fIclient\fP los datos del dispositivo servidor 
.br
\fIstrin\fP el commando recibido
.RE
.PP
\fBReturns:\fP
.RS 4
IRC_OK si fue bien, otra cosa si no
.RE
.PP
.PP
 
.SS "commandAway"
commando Away permite al usuario marcarse como ausente
.PP
\fBParameters:\fP
.RS 4
\fIsocket\fP el socket del usuario a ver 
.br
\fIclient\fP los datos del dispositivo cliente 
.br
\fIserver\fP los datos del dispositivo servidor 
.br
\fIstrin\fP el commando recibido
.RE
.PP
\fBReturns:\fP
.RS 4
IRC_OK si fue bien, otra cosa si no
.RE
.PP
.PP
 
.SS "commandWho"
commando WHO
.PP
\fBParameters:\fP
.RS 4
\fIsocket\fP el socket del usuario a ver 
.br
\fIclient\fP los datos del dispositivo cliente 
.br
\fIserver\fP los datos del dispositivo servidor 
.br
\fIstrin\fP el commando recibido
.RE
.PP
\fBReturns:\fP
.RS 4
IRC_OK si fue bien, otra cosa si no
.RE
.PP
.PP
 
.SS "megaSend"
envia un comando en masa envia un comando a cada uno de los clientes especificados en la lista de nicks
.PP
\fBParameters:\fP
.RS 4
\fIcommand\fP el comando a enviar en masa 
.br
\fInicks\fP la lista con los nicks a quienes hemos de enviar el comando 
.br
\fInum\fP la longitud de la lista de nicks
.RE
.PP
\fBReturns:\fP
.RS 4
IRC_OK si fue bien, otra cosa si no
.RE
.PP
.PP
 
.SH "Author"
.PP 
Generated automatically by Doxygen for Redes2 from the source code\&.
