.TH "threadAudioArgs" 3 "Sun May 7 2017" "Redes2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
threadAudioArgs \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "int \fBport\fP"
.br
.ti -1c
.RI "char * \fBhostname\fP"
.br
.ti -1c
.RI "char * \fBsender\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 13 of file G-2301-05-P2-basicCommandsFromServer\&.c\&.
.SH "Field Documentation"
.PP 
.SS "char* hostname"

.PP
Definition at line 15 of file G-2301-05-P2-basicCommandsFromServer\&.c\&.
.SS "int port"

.PP
Definition at line 14 of file G-2301-05-P2-basicCommandsFromServer\&.c\&.
.SS "char* sender"

.PP
Definition at line 16 of file G-2301-05-P2-basicCommandsFromServer\&.c\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Redes2 from the source code\&.
